### ISSUE TITLE
Bluetooth not available after second boot

### ISSUE THREAD

**Issue by artpoz** [ev3dev/ev3dev#1266] opened 2019-04-24 16:43 UTC
**Describe the bug**
Bluetooth not available  after second boot

**To Reproduce**
1. First boot 
2. Wireless an Networks -> Bluetooth -> Power on, Visible on, -> Start scan  (PS+Share on PS4 Gamepad) -> Down to Wireless Controller (select) -> Pair
3. Shutdown -> Power off
4. Second boot
5. Wireless an Networks -> Bluetooth

**Result**
Not available

**Expected behavior**
Access to bluetooth after second boot.

```
Image file:         ev3dev-stretch-ev3-generic-2019-03-03
Kernel version:     4.14.96-ev3dev-2.3.2-ev3
Brickman:           0.10.0
BogoMIPS:           148.88
Bluetooth:          2.1
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165343C8E0
BOARD_INFO_TYPE=main
```

**Comment by dlech** [comment] 2019-04-25 01:35
Duplicate of #925

**Closed as completed by dlech** 2019-04-25 01:35 UTC
Labels: duplicate
