### ISSUE TITLE
Outdated NodeJS

### ISSUE THREAD

**Issue by typemismatch** [ev3dev/ev3dev#561] opened 2016-03-07 16:05 UTC
Is there a way to get an updated NodeJS build running? I tried everything including pulling source and binaries from NodeJS, anything precompiled doesn't run. I tried apt-get source updates but still just end up with v0.10.29 - some things like Map were introduced in v0.11x+

Is there a trick to getting this updated? thanks.

**Comment by dlech** [comment] 2016-03-07 17:24
Duplicate of #448.

**Closed by dlech** 2016-03-07 17:24 UTC
