### ISSUE TITLE
dIMU driver?

### ISSUE THREAD

**Issue by antonvh** [ev3dev/ev3dev#546] opened 2016-02-09 16:48 UTC
I want to add a driver for the dexter industries dIMU. How do I do that? There is python code that easily explains how you can read from the sensor here: https://github.com/DexterInd/BrickPi_Python/blob/master/Sensor_Examples/DI-dIMU_Test.py

This code has all values and addresses.

**Comment by dlech** [comment] 2016-02-09 17:01
Duplicate of #81. See <http://www.ev3dev.org/contribute/#write-a-driver>. There are several IMU NXT/I2C drivers already you can copy from in <https://github.com/ev3dev/lego-linux-drivers/blob/master/sensors/nxt_i2c_sensor_defs.c>/

Please leave any further comments in #81.

**Closed by dlech** 2016-02-09 17:01 UTC
