### ISSUE TITLE
Edimax WIFI not working on kernel 4.4.13

### ISSUE THREAD

**Issue by tjhgit** [ev3dev/ev3dev#693] opened 2016-07-03 07:34 UTC
### System information:

* I am using:     LEGO MINDSTORMS EV3

* I installed ev3dev using this image file: ev3-ev3dev-jessie-2015-12-30.img

* My kernel version is: 4.4.13-12-ev3dev-ev3 (via apt-get dist-upgrade)

* My host computer is running: OS X 10.11.5

* I am connecting using: USB

### About my issue:

Here is the output of lsusb:
Bus 001 Device 002: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]

The EDIMAX wifi is no more working. Worked on the previous kernel version. Reason probably is that there is no module for this kernel. See:
http://archive.ev3dev.org/debian/pool/main/r/rtl8192cu/

Can you help me out how I can compile a module for the new kernel?
Should I try the approach explained here:
https://adamscheller.com/systems-administration/rtl8192cu-fix-wifi/
Does not work ... :(

This is related to:
https://github.com/ev3dev/ev3dev/issues/669
I do not know how to build a new kernel as suggest here.

**Comment by dlech** [comment] 2016-07-03 18:03
Duplicate of #681 and #669.

If you would like to build your own kernel, see https://github.com/ev3dev/ev3dev-buildscripts

**Closed by dlech** 2016-07-03 18:03 UTC
