### ISSUE TITLE
lms2012 not working?

### ISSUE THREAD

**Issue by Vienhackar** [ev3dev/ev3dev#1051] opened 2018-03-15 21:08 UTC
So I was trying to get lms2012 to run, I downloaded stretch and installed lms2012 and ran sudo lms2012
_______________________________________________________________________________________________________________
robot@ev3dev:~$ sudo lms2012
[sudo] password for robot:

** (process:925): WARNING **: Could not start graphics: No supported video driver plugins found

** (process:925): WARNING **: Falling back to memory driver

** (process:925): ERROR **: Could not load memory driver
Trace/breakpoint trap
**robot@ev3dev:~$**
_______________________________________________________________________________________________________________

**Comment by dlech** [comment] 2018-03-16 01:50
This sounds like a duplicate of #1050.

**Closed as completed** 2018-03-16 02:30 UTC
