### ISSUE TITLE
Touchscreen for PiStorms-v2 not working

### ISSUE THREAD

**Issue by dungba88** [ev3dev/ev3dev#1084] opened 2018-05-01 20:15 UTC
### What are you trying to do?
After installing ev3dev for pistorms using this guide (http://docs.ev3dev.org/en/ev3dev-stretch/getting-started/pistorms.html), with latest image (2017-09-14) and config.txt file modified as instructed, I started the PiStorms and tried to use with the included touch pen.

### What did you expect to happen?
Touch pen should work and should be able to 'click' the menu item.

### What actually happened?
The screen shows up (with usual menu item like File Browser, etc). But touch pen not responding. Nothing happen when using it. The Go button in PiStorms works fine.

### What hardware and software are you using (including version numbers)?
ev3dev-jessie-rpi2-generic-2017-09-14. Pi 3 Model B. PiStorms-v2.

Note: the official OS works fine with touch pen.

**Comment by dlech** [comment] 2018-05-02 02:13
Duplicate of #426.

You can actually write your own programs with touchscreen support currently, but yes, it is not working in the Brickman program yet.

**Closed as completed by dlech** 2018-05-02 02:13 UTC
Labels: duplicate
