### ISSUE TITLE
Brickman shows connected even after usb cable removed

### ISSUE THREAD

**Issue by ameysutavani** [ev3dev/ev3dev#244] opened 2015-01-08 04:56 UTC
When I remove the usb connection this happens :
![img_20150108_101807](https://cloud.githubusercontent.com/assets/5621205/5658048/99ead788-9720-11e4-8056-afb32e04cf0b.jpg)
![img_20150108_101818](https://cloud.githubusercontent.com/assets/5621205/5658051/a85e7338-9720-11e4-91de-d017e0ec6e75.jpg)

**Comment by dlech** [comment] 2015-01-08 18:15
The IP address should probably go away when you disconnect the cable. However, the checkbox next to Gadget in the Networking menu just means that Gadget is *enabled*, it does not have anything to do with the connection state.

P.S. You can use `fbgrab <some-name>.png` to get screenshots on the EV3.

**Comment by ameysutavani** [comment] 2015-01-09 04:26
ok

**Comment by ameysutavani** [comment] 2015-01-09 04:33
no the ip address does not go away when i disconnect the usb cable

I have now updated to 3.16.7 ckt with brickman 0.3.0, still the bug persists

**Comment by dlech** [comment] 2015-01-21 04:29
I've dug into this a bit. The problem is actually on the kernel level, so nothing we can do about it in brickman. Basically the problem is [this](http://e2e.ti.com/support/embedded/linux/f/354/t/65332). The code mentioned in the link is the `da8xx_musb_set_mode` function [here](https://github.com/ev3dev/ev3dev-kernel/blob/ev3dev-jessie/drivers/usb/musb/da8xx.c#L386). The change would be deleting everything in the function body except for `return 0`. However, I am concerned that making the changes might cause a regression on #43.

If anyone wants to compile their own kernel and try this, let me know.

**Comment by dlech** [comment] 2015-01-21 04:47
This was easy enough that I decided to test it out myself, so I am going to go ahead and plan on including these changes next kernel release. It would be nice if 1 or 2 people using Windows would try it out before then to make sure we haven't caused a regression, but I think it should be OK.

**Comment by rhempel** [comment] 2015-01-21 12:50
I've got a Windows 8 Tablet  to test this out on, and a Windows 7 VM as well

**Comment by WasabiFan** [comment] 2015-01-21 16:40
@dlech Small nit-pick: I think "commited" is supposed to be spelled with two "t"s (in the label name).

**Comment by dlech** [comment] 2015-02-22 22:53
Fix has been release in [v3.16.7-ckt6-ev3dev1](http://www.ev3dev.org/news/2015/02/22/Kernel-Release-v3.16.7-ckt6-ev3dev1/).

**Closed by dlech** 2015-02-22 22:53 UTC
Labels: bug, fix committed, kernel
