### ISSUE TITLE
ev3dev doesn't support an AC600 wifi dongle

### ISSUE THREAD

**Issue by cho934** [ev3dev/ev3dev#1037] opened 2018-02-11 22:07 UTC
Hi,
For the next cup of robotic in March, we are allowed to use Wifi ac 5Ghz.

I've just tried 3 wiki dongles unsuccessfully :(

Netgear A6100
An AC600 USB adapter
TP-link AC450 nano USB adapter

Wifi is not available in brickman.
What can I do to solve quickly this problem ?

**Comment by dlech** [comment] 2018-02-12 00:08
See #1021

**Comment by cho934** [comment] 2018-02-12 14:42
A little bit difficult to understand :( and I don't want to compile everything...
It's working with a new kernel, isn't it ?

Is it possible to have a resume ?

**Comment by dlech** [comment] 2018-02-12 16:15
There are some Debian packages attached to that issue for specific kernel versions.

**Comment by dlech** [comment] 2018-02-12 16:16
Not sure what you mean by "resume"

**Comment by cho934** [comment] 2018-02-12 17:47
it means the final "how to" ?

**Comment by dlech** [comment] 2018-02-12 18:47
https://github.com/ev3dev/ev3dev/issues/1021#issuecomment-354867225

- download the zip file
- unzip it
- copy the .deb file to your EV3
- `dpkg -i <name-of-package>.deb`

**Comment by dlech** [comment] 2018-03-22 21:16
Closing as duplicate of #1021

**Closed as completed by dlech** 2018-03-22 21:16 UTC
Labels: duplicate, Wi-Fi
