### ISSUE TITLE
ImportError: No module named ev3dev

### ISSUE THREAD

**Issue by ghost** [ev3dev/ev3dev#1063] opened 2018-03-30 21:53 UTC
Hi! I'm having a problem with running python scripts on my lego brick with ev3dev. I didn't use it for quite a time and now I'm not able to run any scripts because of error below. Any ideas why this might be happening? It looks like there are some problems with ev3dev library but I have no idea what it might be 

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from ev3dev.ev3 import *
ImportError: No module named ev3dev.ev3

**Comment by dlech** [comment] 2018-03-30 22:00
duplicate of #1058

you need to use python3.

**Closed as completed** 2018-05-03 16:37 UTC
Labels: duplicate
