### ISSUE TITLE
Cannot Read  Lego's Energy Display (9668) sensor from Python

### ISSUE THREAD

**Issue by MVOLT74** [ev3dev/ev3dev#665] opened 2016-06-05 22:56 UTC
I am trying to read the Lego's Energy Display (9668) sensor connected to a EV3 using Python script . 

I have tried using python sensor examples but have not been able to make them work. 
When I try the following code I get no error but the connected value is always return false
```
from ev3dev.auto import *
d = Sensor()
myVar = str(d.connected)
print myVar

```
The Energy Meter is the only device connected to the EV3.  When I use the Device Browser on the EV3 I cannot see the device listed in the Sensors section.

Can you please help me?

**Comment by dlech** [comment] 2016-06-05 23:24
Duplicate of #626. We have fixed it, but we have not released a kernel that contains the fix. If you want to use it before we release a new kernel, you will have to [compile a kernel yourself](https://github.com/ev3dev/ev3dev-buildscripts/). And no, I don't know when the next kernel release will be.

**Closed by dlech** 2016-06-05 23:24 UTC
Labels: duplicate
