### ISSUE TITLE
Motors change name after apt-get dist-upgrade

### ISSUE THREAD

**Issue by Grumpy-Mike** [ev3dev/ev3dev#197] opened 2014-11-06 04:52 UTC
Before I did a "apt-get dist-upgrade" the motors were accessible with the path:-
/sys/class/tacho-motor/tacho-motor0/
Like it says in the motor tutorial, but after the path changes to:-
/sys/class/tacho-motor/motor0/

There is error in the wiki/Using-Motors:-
It consistently says plug motor into Port B and the examples use /sys/class/tacho-motor/tacho-motor2/ which is not Port B but Port C

Getting started Wiki
Needs a warning that:-
root@ev3dev:~# apt-get upgrade
Will take over three hours with a fast broadband connection.

**Comment by Grumpy-Mike** [comment] 2015-01-14 15:55
I am having an issue with EV3dev. It seems after running for some time that motor1 disappeares. Sometimes this can happen after 5 minutes sometimes longer. I am using three motors but always motor1 goes. I get the message "No such file or directory" when I try and access it. The motor has been happily working many hundreds of times before this happens.
The brick is being written to over an SSH session controlled by python from a Raspberry Pi. It is controlling a drawing robot.
Also occasionally when I power up with the motors already plugged in the motors are assigned different ports so my code runs incorrectly. 
Has anyone else noticed this sort of behavior?

**Comment by G33kDude** [comment] 2015-01-14 16:02
From [the docs](http://www.ev3dev.org/docs/drivers/tacho-motor-class/):
> Tacho motors can be found at `/sys/class/tacho-motor/motor<N>`, where `<N>` is incremented each time a motor is loaded (it is not related to which port the motor is plugged in to).

**Comment by Grumpy-Mike** [comment] 2015-01-14 16:11
Yes I know that but when the brick starts ( boots ) with the motors already they are normally assigned the same numbers, but very occasionally they are not. 
The main problem is the dissapearing motor, it seems to be reallocated to motor3 from motor1.

**Comment by G33kDude** [comment] 2015-01-14 16:14
It sounds to me like the cable it's on is shorting. See if switching it out for a different cable helps any. Also, it assigning the same numbers every time isn't *normal*, it's *coincidental*. **Do not rely on it**.

**Comment by Grumpy-Mike** [comment] 2015-01-14 16:16
I have tried several cables all with the same results it was the first thing I though of.
"assigning the same numbers every time isn't normal, it's coincidental. Do not rely on it."
So how can you ever write software that knows what motor is what? Do you have to plug everything in and in the right order everytime you boot?

**Comment by G33kDude** [comment] 2015-01-14 16:18
Each directory has a file in it `port_name` or something like that. You can iterate through all the folders until `port_name` is what you're looking for, or you can do as I suggested and use a udev library (like pyudev) to handle finding it for you.

**Comment by Grumpy-Mike** [comment] 2015-01-14 16:25
Is there seriously some one who wrote this, and that thinks it is a good idea?
"or you can do as I suggested " sorry didn't see the suggestion anywhere, I am not very good at Linux and have no idea how to "use a udev library (like pyudev) to handle finding it for you."

**Comment by G33kDude** [comment] 2015-01-14 16:35
>Instead, consider using pyudev to get your motors, as I do in [my pyev3 library](http://github.com/G33kDude/pyev3)

It's not too hard to use pyudev.

```
import pyudev

context = pyudev.Context()
devices = context.list_devices(
    subsystem='tacho-motor',
    PORT='outB',
    TYPE='tacho' # the tacho type, usually 'tacho' or 'minitacho'. Use '*' for wildcard, or omit the parameter.
)
try:
   motorB = devices[0]
except IndexError:
    raise Exception('Device not found')
```

**Comment by Grumpy-Mike** [comment] 2015-01-14 16:50
Thanks for that, but the disconnection / reconnection issue looks like it is a fatal flaw in the whole shooting match. It would have been so easy to allocate a motor to the next free "slot" instead of creating a new one, especially as it looks like this can happen spontaneously. Or I have four leads from two sources all bad. It looks like there is no way back as well, short of rebooting as plugging in and out seem to create higher and higher motor numbers.
I have been over six months on this project looking for an alternative language for the brick, it seems like there is something wrong with all of them I have tried. 
Brick Pi does not move the motors accurately enough, legos is just too difficult to even install on a Mac, after many hours for a hardware chap like me. I thought this one was it, I had a hell of a job getting an SSH session controlled from python but after trying many found paramiko would work. Now this. I think I will sit down and have a little weep.
Thanks anyway.

**Comment by dlech** [comment] 2015-01-14 18:39
@Grumpy-Mike, when are done weeping, if you would like to help make ev3dev better there are some things you can do...

1. Please open a new issue for each separate problem that you have. This helps us keep things sorted out. The original issue here is about motors being renamed. You have pointed out a new problem of a motor disconnecting and reconnecting even though it is not physically disconnected. Please open an new issue for this to help us keep things sorted out. Also, it you think that the current device enumeration (motor0, motor1, ...) is dreadful and should be changed, open a new issue for that as well.
2. When you open new issues, be sure to follow the instructions [here](https://github.com/ev3dev/ev3dev/blob/master/CONTRIBUTING.md). The same link is in the big yellow box that you will see after you click "New Issue". Most importantly, we need to know what kernel version you are using. Also, in the case of the motor, what type of motor is is (large, medium, NXT, 3rd party). Is it running or stopped when this happens? Do you have a link to the program you are using? Anything that could help us reproduce the problem is helpful. If we can't reproduce it, we can't fix it.
3. Understand where we are coming from. We are just enthusiasts, not experts. We would like ev3dev to be super-easy for everyone to use, but we are not there yet and have quite a ways to go. But to us, half the fun is getting there. If you don't at least find some satisfaction in working through these kinds of issues, then ev3dev is not ready for you yet. Come back in a year or so and see how we are doing. On the other hand, if you have some patience and would like to put some effort into helping us (like opening new issues and providing more information), you could could help us make progress - possibly in a direction that if favorable to you.
4. If you original issue is resolved, you can close this issue.

**Comment by rhempel** [comment] 2015-01-14 22:43
@Grumpy-Mike - yes, we are trying to make this work for everyone - the motor numbering is a bit weird, and I struggled mightily before doing it this way. But please believe us when we say it's a good way to do it when you consider that there are other ways to get a motor connected. The `port_name`  attribute is your friend.
We could consider caching port assignments and motor numbers but this would break down on reboot.
That all being said, having a running motor disconnect and reconnect is not cool because, well, it changes the motor number underneath you.
Please also tell us a little about the running condion of Motor 1 when it disconnects - ie which physical port is it plugged into, how fast is it running, it it heavily loaded, what about the other motors, ports, heavily loaded etc.
Also try switching physical motors, maybe there is something wrong with the sense resistor in your motor, or your brick.
Finally,  we may have broken something in the autodetect code, it used to be that you could never disconnect a motor unless it was in the idle state.

**Comment by rhempel** [comment] 2015-01-14 22:44
On another note, you mention struggling to get an ssh session controlled by Python. Are you trying to control the brick from a python program on your host PC? Or are you running Python right on the brick? Please open a separate issue to describe this problem a bit better.

**Comment by dlech** [comment] 2015-04-16 03:48
Calling this "wontfix" for now... but we can repoen if this is still a concern for anyone.

**Closed by dlech** 2015-04-16 03:48 UTC
Labels: documentation, motors, wontfix
