### ISSUE TITLE
I can't see any motor & sensor connected to BrickPi+

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#581] opened 2016-03-23 16:24 UTC
### System information: 

* I am using: Dexter Industries [BrickPi BrickPi+]
* I installed ev3dev using this image file: ev3-ev3dev-jessie-2015-12-30.img
* My kernel version is: 4.1.15-9-ev3dev-rpi2

### About my issue:

I am trying to use a motor and a sensor with brickpi but I can see anything in /sys/class:

``` bash
robot@ev3dev:/sys/class$ ls
backlight        dma          input             leds          pwm          sound       vc-cma
bcm2708_vcio     gpio         iscsi_connection  lego-port     raw          spi_master  vc-mem
bcm2835-gpiomem  graphics     iscsi_endpoint    mem           rfkill       spidev      vc-sm
bdi              hidraw       iscsi_host        misc          rtc          thermal     vchiq
block            i2c-adapter  iscsi_iface       mmc_host      scsi_device  tty         vtconsole
bsg              i2c-dev      iscsi_session     net           scsi_disk    uio         watchdog
devcoredump      ieee80211    iscsi_transport   power_supply  scsi_host    vc
```

I tried to see the lego-port, but I can't see anything:

``` bash
robot@ev3dev:/sys/class$ cd lego-port/
robot@ev3dev:/sys/class/lego-port$ ls
robot@ev3dev:/sys/class/lego-port$ 
```

What is the problem?

**Comment by dlech** [comment] 2016-03-23 16:26
You probably did not enable BrickPi in `config.txt`. 

Duplicate of #529

**Closed by dlech** 2016-03-23 16:26 UTC
